module.exports = function(app)
{
	app.get('/',function(req,res){
		res.render('index.html')
	});
	app.get('/about',function(req,res){
		res.render('about.html');
	});
	app.get('/signin',function(req,res){
		res.render('signin.html');
	});
	app.get('/product',function(req,res){
		res.render('product.html');
	});
	app.get('/upload',function(req,res){
		res.render('upload.html');
	});
	app.get('/product_info',function(req,res){
		res.render('product_info.html');
	});
	app.get('/mypage',function(req,res){
		res.render('mypage.html');
	});
}
